AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/*'
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - hash
    - array
    - heredoc
    - method_call
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/RescueStandardError:
  EnforcedStyle: implicit
