AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/RescueStandardError:
  EnforcedStyle: implicit
