AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/RescueStandardError:
  EnforcedStyle: implicit
